build:
    environment:
        php:
            version: 5.6.25
    dependencies:
        before:
            - sudo composer self-update
            - composer global require "fxp/composer-asset-plugin:^1.2"
imports:
    - php
filter:
    excluded_paths:
        - vendor/*
