build:
    environment:
        php:
            version: 5.6
    dependencies:
        before:
            - sudo composer self-update
            - composer config -g repositories.asset-packagist composer https://asset-packagist.org
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'
imports:
    - php
tools:
    php_cpd: false
    php_sim: false
filter:
    excluded_paths:
        - docs/*
        - tests/*
        - vendor/*
