sudo: false
language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
matrix:
    include:
        - php: 5.6
          env:
              - PHPUNIT_COVERAGE="--coverage-clover=coverage.xml"
cache:
    directories:
        - vendor
install:
    - travis_retry composer config -g repositories.asset-packagist composer https://asset-packagist.org
    - travis_retry composer update --no-interaction
    - composer info -i
script:
    - vendor/bin/phpunit $PHPUNIT_COVERAGE
after_script:
    - |
      if [ -n "$PHPUNIT_COVERAGE" ]; then
          travis_retry wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.xml
      fi
    - bash <(curl -s https://codecov.io/bash)
